<?php
/**
 * @file
 * piwik_autologin.module
 * @brief .module file for the Piwik Autologin Drupal module.
 * @author Romain Ducher <r.ducher@agence-codecouleurs.fr>
 * @license https://www.gnu.org/licenses/gpl-3.0.txt
 * @section LICENSE
 *
 * Copyright 2014 Code Couleurs
 *
 * This file is part of Piwik Autologin.
 *
 * Piwik Autologin is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option)
 * any later version.
 *
 * Piwik Autologin is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS OR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Piwik Autologin. If not, see <http://www.gnu.org/licenses/>.
 */

require_once 'piwik_autologin.backend.inc';

if (!class_exists('PiwikUser')) {
  require_once 'piwik_autologin.piwik_user.inc';
}

/**
 * Implementing "hook_menu".
 */
function piwik_autologin_menu() {
  $items = array();
  \piwik_autologin\set_module_configuration_menu($items);
  return $items;
}

/**
 * Implementing hook_user_login.
 *
 * Retrieve the Logme URL for Piwik
 * @see https://api.drupal.org/api/drupal/modules!user!user.api.php/function/hook_user_login/7
 */
function piwik_autologin_user_login(&$edit, $account) {
  \piwik_autologin\set_logme_url($account->uid);
}

/**
 * Implementing hook_page_build.
 *
 * @param array $page
 *   Page to build.
 */
function piwik_autologin_page_build(&$page) {
  \piwik_autologin\embed_piwik_iframe($page);
}
